spring:
  config:
    import:
     - optional:file:./config/secret.yaml
     - optional:file:./config/telegram.yaml
     - optional:file:./config/openai.yaml

logging:
  level:
    org.springframework.boot.context.config: INFO
    root: INFO
    org.example: DEBUG